# Generated by Django 4.1.4 on 2023-01-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_comment_bid_auction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Intelligence', 'Intelligence'), ('Agility', 'Agility')], default='Strength', max_length=20),
        ),
    ]
